{
  level: 'error',
  message: 'Error occurred while getting tenant useres in getAllTenantUsers controller {"message":"Request failed with status code 401","name":"AxiosError","stack":"AxiosError: Request failed with status code 401\\n    at settle (/home/casualdesert/Documents/code/RecruitementApp/Backend/RBackend/node_modules/axios/dist/node/axios.cjs:1855:12)\\n    at Unzip.handleStreamEnd (/home/casualdesert/Documents/code/RecruitementApp/Backend/RBackend/node_modules/axios/dist/node/axios.cjs:2712:11)\\n    at Unzip.emit (node:events:525:35)\\n    at endReadableNT (node:internal/streams/readable:1359:12)\\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)","config":{"transitional":{"silentJSONParsing":true,"forcedJSONParsing":true,"clarifyTimeoutError":false},"adapter":["xhr","http"],"transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1,"env":{},"headers":{"Accept":"application/json, text/plain, */*","Authorization":"Bearer Error: getaddrinfo EAI_AGAIN login.microsoftonline.com","User-Agent":"axios/1.2.1","Accept-Encoding":"gzip, compress, deflate, br"},"method":"get","url":"https://graph.microsoft.com/v1.0/users"},"code":"ERR_BAD_REQUEST","status":401}:',
  timestamp: '2023-01-23T02:56:23.069Z'
}
{
  name: 'SequelizeConnectionError',
  parent: Error: Unknown database 'r'
      at Packet.asError (C:\Users\Sanket G\Downloads\recruitment-app-backend\node_modules\mysql2\lib\packets\packet.js:728:17)
      at ClientHandshake.execute (C:\Users\Sanket G\Downloads\recruitment-app-backend\node_modules\mysql2\lib\commands\command.js:29:26)
      at Connection.handlePacket (C:\Users\Sanket G\Downloads\recruitment-app-backend\node_modules\mysql2\lib\connection.js:456:32)
      at PacketParser.onPacket (C:\Users\Sanket G\Downloads\recruitment-app-backend\node_modules\mysql2\lib\connection.js:85:12)
      at PacketParser.executeStart (C:\Users\Sanket G\Downloads\recruitment-app-backend\node_modules\mysql2\lib\packet_parser.js:75:16)
      at Socket.<anonymous> (C:\Users\Sanket G\Downloads\recruitment-app-backend\node_modules\mysql2\lib\connection.js:92:25)
      at Socket.emit (node:events:513:28)
      at addChunk (node:internal/streams/readable:315:12)
      at readableAddChunk (node:internal/streams/readable:289:9)
      at Socket.Readable.push (node:internal/streams/readable:228:10) {
    code: 'ER_BAD_DB_ERROR',
    errno: 1049,
    sqlState: '42000',
    sqlMessage: "Unknown database 'r'",
    sql: undefined
  },
  original: Error: Unknown database 'r'
      at Packet.asError (C:\Users\Sanket G\Downloads\recruitment-app-backend\node_modules\mysql2\lib\packets\packet.js:728:17)
      at ClientHandshake.execute (C:\Users\Sanket G\Downloads\recruitment-app-backend\node_modules\mysql2\lib\commands\command.js:29:26)
      at Connection.handlePacket (C:\Users\Sanket G\Downloads\recruitment-app-backend\node_modules\mysql2\lib\connection.js:456:32)
      at PacketParser.onPacket (C:\Users\Sanket G\Downloads\recruitment-app-backend\node_modules\mysql2\lib\connection.js:85:12)
      at PacketParser.executeStart (C:\Users\Sanket G\Downloads\recruitment-app-backend\node_modules\mysql2\lib\packet_parser.js:75:16)
      at Socket.<anonymous> (C:\Users\Sanket G\Downloads\recruitment-app-backend\node_modules\mysql2\lib\connection.js:92:25)
      at Socket.emit (node:events:513:28)
      at addChunk (node:internal/streams/readable:315:12)
      at readableAddChunk (node:internal/streams/readable:289:9)
      at Socket.Readable.push (node:internal/streams/readable:228:10) {
    code: 'ER_BAD_DB_ERROR',
    errno: 1049,
    sqlState: '42000',
    sqlMessage: "Unknown database 'r'",
    sql: undefined
  },
  level: 'error',
  timestamp: '2023-01-23T06:29:12.061Z'
}
{
  level: 'error',
  message: `Error occurred while finding user in checkUserExistInApp middleware {"name":"SequelizeConnectionError","parent":{"code":"ER_BAD_DB_ERROR","errno":1049,"sqlState":"42000","sqlMessage":"Unknown database 'r'"},"original":{"code":"ER_BAD_DB_ERROR","errno":1049,"sqlState":"42000","sqlMessage":"Unknown database 'r'"}}:`,
  timestamp: '2023-01-23T06:29:26.253Z'
}
{
  level: 'error',
  message: `Error occurred while finding user in checkUserExistInApp middleware {"name":"SequelizeConnectionError","parent":{"code":"ER_BAD_DB_ERROR","errno":1049,"sqlState":"42000","sqlMessage":"Unknown database 'r'"},"original":{"code":"ER_BAD_DB_ERROR","errno":1049,"sqlState":"42000","sqlMessage":"Unknown database 'r'"}}:`,
  timestamp: '2023-01-23T06:29:26.266Z'
}
{
  name: 'SequelizeConnectionError',
  parent: Error: Unknown database 'recruiter_app_tes'
      at Packet.asError (C:\Users\Sanket G\Downloads\recruitment-app-backend\node_modules\mysql2\lib\packets\packet.js:728:17)
      at ClientHandshake.execute (C:\Users\Sanket G\Downloads\recruitment-app-backend\node_modules\mysql2\lib\commands\command.js:29:26)
      at Connection.handlePacket (C:\Users\Sanket G\Downloads\recruitment-app-backend\node_modules\mysql2\lib\connection.js:456:32)
      at PacketParser.onPacket (C:\Users\Sanket G\Downloads\recruitment-app-backend\node_modules\mysql2\lib\connection.js:85:12)
      at PacketParser.executeStart (C:\Users\Sanket G\Downloads\recruitment-app-backend\node_modules\mysql2\lib\packet_parser.js:75:16)
      at Socket.<anonymous> (C:\Users\Sanket G\Downloads\recruitment-app-backend\node_modules\mysql2\lib\connection.js:92:25)
      at Socket.emit (node:events:513:28)
      at addChunk (node:internal/streams/readable:315:12)
      at readableAddChunk (node:internal/streams/readable:289:9)
      at Socket.Readable.push (node:internal/streams/readable:228:10) {
    code: 'ER_BAD_DB_ERROR',
    errno: 1049,
    sqlState: '42000',
    sqlMessage: "Unknown database 'recruiter_app_tes'",
    sql: undefined
  },
  original: Error: Unknown database 'recruiter_app_tes'
      at Packet.asError (C:\Users\Sanket G\Downloads\recruitment-app-backend\node_modules\mysql2\lib\packets\packet.js:728:17)
      at ClientHandshake.execute (C:\Users\Sanket G\Downloads\recruitment-app-backend\node_modules\mysql2\lib\commands\command.js:29:26)
      at Connection.handlePacket (C:\Users\Sanket G\Downloads\recruitment-app-backend\node_modules\mysql2\lib\connection.js:456:32)
      at PacketParser.onPacket (C:\Users\Sanket G\Downloads\recruitment-app-backend\node_modules\mysql2\lib\connection.js:85:12)
      at PacketParser.executeStart (C:\Users\Sanket G\Downloads\recruitment-app-backend\node_modules\mysql2\lib\packet_parser.js:75:16)
      at Socket.<anonymous> (C:\Users\Sanket G\Downloads\recruitment-app-backend\node_modules\mysql2\lib\connection.js:92:25)
      at Socket.emit (node:events:513:28)
      at addChunk (node:internal/streams/readable:315:12)
      at readableAddChunk (node:internal/streams/readable:289:9)
      at Socket.Readable.push (node:internal/streams/readable:228:10) {
    code: 'ER_BAD_DB_ERROR',
    errno: 1049,
    sqlState: '42000',
    sqlMessage: "Unknown database 'recruiter_app_tes'",
    sql: undefined
  },
  level: 'error',
  timestamp: '2023-01-23T06:30:44.291Z'
}
{
  level: 'error',
  message: `Error occurred while finding user in checkUserExistInApp middleware {"name":"SequelizeConnectionError","parent":{"code":"ER_BAD_DB_ERROR","errno":1049,"sqlState":"42000","sqlMessage":"Unknown database 'recruiter_app_tes'"},"original":{"code":"ER_BAD_DB_ERROR","errno":1049,"sqlState":"42000","sqlMessage":"Unknown database 'recruiter_app_tes'"}}:`,
  timestamp: '2023-01-23T06:30:52.643Z'
}
{
  level: 'error',
  message: `Error occurred while finding user in checkUserExistInApp middleware {"name":"SequelizeConnectionError","parent":{"code":"ER_BAD_DB_ERROR","errno":1049,"sqlState":"42000","sqlMessage":"Unknown database 'recruiter_app_tes'"},"original":{"code":"ER_BAD_DB_ERROR","errno":1049,"sqlState":"42000","sqlMessage":"Unknown database 'recruiter_app_tes'"}}:`,
  timestamp: '2023-01-23T06:30:52.656Z'
}
